feat: form-data
typescord/famfor pull request #2
Opened 2021-04-26 01:16 UTC by Mesteery

2021-04-26 07:44 UTC, Aakodal requested changes

2021-04-26 07:44 UTC, Aakodal commented on README.md
> +A `value` is considered as file if it's a `ReadStream` or if it have a `filename`.
```suggestion
A `value` is considered as file if it's a `ReadStream` or if it has a `filename`.
```

2021-04-26 07:44 UTC, Aakodal commented on README.md
> +If the `type` is present, it will be always put (even if the `filename` is not present).
```suggestion
If the `type` is present, it will always be put (even if the `filename` is not present).
```

2021-04-26 07:44 UTC, Aakodal commented on README.md
> +You can send queries via HTTP clients that supports headers setting `stream.Readable` stream as body.
```suggestion
You can send queries via HTTP clients that support headers setting `stream.Readable` stream as body.
```

2021-04-26 07:44 UTC, Aakodal commented on README.md
> +// when the value is a Readable, you **should** specify it's size (if want to have a correct length)
```suggestion
// when the value is a Readable, you **should** specify its size (if you want to have a correct length)
```

2021-04-26 07:44 UTC, Aakodal commented on README.md
> +// you can get the size simply with (it's already included in the `headers`) :
```suggestion
// you can get the size (already included in the `headers`) simply with:
```

2021-04-26 07:44 UTC, Aakodal commented on src/index.test.ts
> +	it('should be instance of Map', () => {
```suggestion
	it('should be an instance of Map', () => {
```

2021-04-26 07:44 UTC, Aakodal commented on src/index.test.ts
> +	it("it should have some undefined Map's methods", () => {
```suggestion
	it("should have some undefined Map's methods", () => {
```

2021-04-26 07:44 UTC, Aakodal commented on src/index.test.ts
> +	it('should be correct', () => {
```suggestion
	it('should return the correct length', () => {
```

2021-04-26 07:44 UTC, Aakodal commented on src/index.ts
> +	entries(): any;
Should unknown over any not be preferred?

2021-04-26 07:44 UTC, Aakodal commented on src/index.ts
> + * // when the value is a Readable, you **should** specify it's size (if want to have a correct length)
```suggestion
 * // when the value is a Readable, you **should** specify its size (if want to have a correct length)
```

2021-04-26 07:44 UTC, Aakodal commented on src/index.ts
> +interface FormDataMap extends Omit<Map<string, FormDataField[]>, 'forEach' | 'set'> {
This actually breaks all OOP concepts. FormData should not extend Map if it doesn't apply its methods

2021-04-26 07:44 UTC, Aakodal commented on src/index.ts
> +	private async *release(): AsyncGenerator<Buffer | string, any, undefined> {
unknown over any?

2021-04-26 07:44 UTC, Aakodal commented on src/index.ts
> +		// @ts-expect-error ignoring this is the best solution.
Why? What happens? Be clearer here.

2021-04-26 07:44 UTC, Aakodal commented on src/index.ts
> +	 * Returns all the values associated with
```suggestion
	 * Return all the values associated with
```

2021-04-26 07:44 UTC, Aakodal commented on src/index.ts
> +		return 'FormData';
```suggestion
		return '[FormData]';
```

2021-04-26 11:41 UTC, Mesteery commented on src/index.ts
> +	private async *release(): AsyncGenerator<Buffer | string, any, undefined> {
I can't use `unknown` here

2021-04-26 11:42 UTC, Mesteery commented on src/index.ts
> +		// @ts-expect-error ignoring this is the best solution.
Because set doesn't exists for TypeScript (since it's typed as undefined to override Map's methods).
It's a bad idea to extends Map, yes.

2021-04-26 11:43 UTC, Mesteery commented on src/index.ts
> +		return 'FormData';
No, this is not needed.

2021-04-26 12:07 UTC, Aakodal commented on src/index.ts
> +		return 'FormData';
Not needed but a bit more compliant with Object#toString() which returns `[object Object]`, so actually `[object FormData]` would be even better

2021-04-26 12:33 UTC, Mesteery commented on src/index.ts
> +		return 'FormData';
No, it return `[object FormData]`

2021-04-27 12:08 UTC, Aakodal commented on README.md
> +A `value` is considered as file if it's a `ReadStream` or if it has a `filename`.
```suggestion
A `value` is considered as a file if it's a `ReadStream` or if it has a `filename`.
```

2021-04-27 12:08 UTC, Aakodal commented on src/index.test.ts
> +	return stringified;
```suggestion
	readable.setEncoding('utf8');
	let stringified = '';

	for await (const chunk of readable) {
		stringified += chunk;
	}

	return stringified;
```

2021-04-27 12:08 UTC, Aakodal commented on src/index.ts
> + * // a example with Got
```suggestion
 * // an example with Got
```

2021-04-27 12:08 UTC, Aakodal commented on README.md
> +Let's take a look at minimal example with [Got](https://github.com/sindresorhus/got) :
```suggestion
Let's take a look at a minimal example with [Got](https://github.com/sindresorhus/got) :
```

2021-04-27 12:08 UTC, Aakodal commented on src/index.ts
> +		if (filename) {
```suggestion
		let type = options.type;

		if (filename) {
```

2021-04-27 12:12 UTC, Mesteery commented on src/index.test.ts
> +	return stringified;
it's already lisible without.

2021-04-27 12:14 UTC, Aakodal approved these changes

2021-04-27 12:29 UTC, merged